# Generated by Django 5.1.7 on 2025-03-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_alter_offer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferWallPopupOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popup_assignments",
                        to="admin_panel.offer",
                    ),
                ),
                (
                    "offer_wall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popup_assignments",
                        to="admin_panel.offerwall",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("offer_wall", "offer")},
            },
        ),
    ]
