# Generated by Django 5.1.7 on 2025-03-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_offerwallpopupoffer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="offerwalloffer",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="offer",
            name="name",
            field=models.CharField(
                choices=[
                    ("Loanplus", "Loanplus"),
                    ("SgroshiCPA2", "SgroshiCPA2"),
                    ("Novikredyty", "Novikredyty"),
                    ("TurboGroshi", "TurboGroshi"),
                    ("Crypsee", "Crypsee"),
                    ("Suncredit", "Suncredit"),
                    ("Lehko", "Lehko"),
                    ("Monto", "Monto"),
                    ("Limon", "Limon"),
                    ("Amigo", "Amigo"),
                    ("FirstCredit", "FirstCredit"),
                    ("Finsfera", "Finsfera"),
                    ("Pango", "Pango"),
                    ("Treba", "Treba"),
                    ("StarFin", "StarFin"),
                    ("BitCapital", "BitCapital"),
                    ("SgroshiCPL", "SgroshiCPL"),
                    ("LoviLave", "LoviLave"),
                    ("Prostocredit", "Prostocredit"),
                    ("Sloncredit", "Sloncredit"),
                    ("Clickcredit", "Clickcredit"),
                    ("Credos", "Credos"),
                    ("Dodam", "Dodam"),
                    ("SelfieCredit", "SelfieCredit"),
                    ("Egroshi", "Egroshi"),
                    ("Alexcredit", "Alexcredit"),
                    ("SgroshiCPA1", "SgroshiCPA1"),
                    ("Tengo", "Tengo"),
                    ("Credit7", "Credit7"),
                    ("Tpozyka", "Tpozyka"),
                    ("Creditkasa", "Creditkasa"),
                    ("Moneyveo", "Moneyveo"),
                    ("MyCredit", "MyCredit"),
                    ("CreditPlus", "CreditPlus"),
                    ("Miloan", "Miloan"),
                    ("AvansCredit", "AvansCredit"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
